version: "3.9"

services:

  mongo:
    image: mongo:7
    container_name: edurev-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: edurev-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/edurev
    depends_on:
      - mongo

  frontend:
  build: ./frontend
  container_name: edurev-frontend
  ports:
    - "5173:5173"

volumes:
  mongo_data: